#include "mt_pch.h"

#ifndef TINYGLTF_CONFIG_SETTING
#define TINYGLTF_CONFIG_SETTING
    #define TINYGLTF_IMPLEMENTATION
    #define STB_IMAGE_IMPLEMENTATION
    #define STB_IMAGE_WRITE_IMPLEMENTATION
#endif